#!/usr/bin/expect

if {[llength $argv] < 3} {
	puts stderr "Usage: $argv0 in_file out_file pin [pesign params]"
	exit 2
}

log_user 0
lassign $argv in_file out_file pin
spawn pesign -i $in_file \
       --export-signature $out_file --sign \
       -d sha256 {*}[lrange $argv 3 end]
expect "Enter Password *:" {send $pin} timeout {exit 1}
expect "Enter passphrase *:" {send $pin} timeout {exit 1}
lassign [wait] wait_pid spawn_id exec_rc wait_code
if {$exec_rc != 0} {exit 1}
exit $wait_code
