#!/bin/bash

set -u
set -e
set -o pipefail

if [ $# -lt 5 ]; then
	echo "Usage: $0 filename version arch changes_file suite"
	exit 1
fi

IN_TARBALL="$1"	# Tarball to read, compressed with xz
VERSION="$2"
ARCH="$3"
CHANGES="$4"	# Changes file for the upload
SUITE="$5"

error() {
	echo >&2 "E: $*"
	exit 1
}

# Read dak configuration for security or main archive.
# Also determine subdirectory for the suite.
case "$0" in
    /srv/security-master.debian.org/*)
	configdir="/srv/security-master.debian.org/dak/config/debian-security"
	suitedir="$SUITE/updates"
	;;
    /srv/ftp-master.debian.org/*)
	configdir="/srv/ftp-master.debian.org/dak/config/debian"
	suitedir="$SUITE"
	;;
    *)
	error "$0: Can't tell if security or not"
	;;
esac

# Read and trivially validate our configuration
. "$configdir/byhand-code-sign.conf"
for var in DSIGN_BOX_HOST DSIGN_BOX_IMG_DIR \
	SIG_STORAGE_HOST SIG_STORAGE_DIR; do
	test -v "$var" || error "$var is not defined in configuration"
	test -n "${!var}" || error "$var is empty in configuration"
done

# Transfer file to dsigning-box
rsync --checksum "$IN_TARBALL" "$DSIGN_BOX_HOST":"$DSIGN_BOX_IMG_DIR"

# Generate the dettached signatures
OUT_TARBALL=$("$DSIGN_BOX_HOST" "secure-boot-code-sign $IN_TARBALL")

# Get the dettached signatures from dsigning-box
rsync --checksum "$DSIGN_BOX_HOST":"$OUT_TARBALL" /tmp
OUT_TARBALL="${OUT_TARBALL##*/}"

# Transfer the signatures where DDs have access
# FIXME: this is temporary, the signatures should stay in the signing box
rsync --checksum /tmp/"$OUT_TARBALL" "$SIG_STORAGE_HOST":"$SIG_STORAGE_DIR"

echo "I: Signatures created at $SIG_STORAGE_HOST:$SIG_STORAGE_DIR/$OUT_TARBALL"
